import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css"
import { BlogContextProvider } from "../contexts/blogContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="min-h-screen flex flex-wrap content-between overflow-x-hidden">
          <div className="w-full block">
            <BlogContextProvider>
              {children}
            </BlogContextProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
