export const metadata = {
    title: "Files | About Files",
    description: "Generated by create next app",
};

export default  function FileId({ params }) {

    const paramsObj =  params
    const { fileId } = paramsObj
    console.log("fileId" ,fileId);

    return (
        <div>
            <h1>Hey You learned Catch All Routes</h1>
            <h2>File: <i>{fileId?.join("/")}</i></h2>
            <h3>Difference between [...fileId] & [[...fileId]]</h3>

            <h4> [...fileId] (Catch-all Route)</h4>
            <ol>
                <li>This matches multiple segments in a URL.</li>
                <li>It creates a dynamic route that captures one or more parts of the URL as an array.

                </li>
            </ol>
            <h4>[[...fileId]] (Optional Catch-all Route) </h4>
            <ol>
                <li>Similar to [...fileId], but it allows the route to match when no parameter is provided.

                </li>
                <li>If no parameters are passed, fileId will be undefined.

                </li>
            </ol>

            <h1>Don't Use Optional in Root Directory</h1>

            <h2>Example Routes:</h2>
            <ul>
                <li>app/all-files/page.js - Static route for /all-files</li>
                <li>app/files/[[...fileId]]/page.js - Optional catch-all route for /files and /files/some-id</li>
            </ul>
        </div>
    )
}