export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <>
      <h1> This is about page</h1>
      <p>THis is About page description</p>
      
    </>
  );
}
